Added Main Readme and env file for build
IITH-Compilers/ml-llvm-project pull request #34
Opened 2024-02-02 14:11 UTC by mvvsmk

I have described the project in brief and have given instructions about the build and also added one onnx command to invoke each ML driven optimization. I have also added the env file required for the build in the home directory.

2024-02-02 14:15 UTC, mvvsmk commented
There is one issue that is not resolved and that is of the `ml-config-folder` people are still copying it from Pramana , how would you like me to incorporate it into the readme

2024-02-28 11:07 UTC, svkeerthy requested changes

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +    - Requirements
Please add links to each step

2024-02-28 11:07 UTC, svkeerthy commented on README.md
Please add about IR2Vec here

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +* LLVM (10.X) - [src](https://github.com/llvm/llvm-project/tree/release/10.x), [release](https://releases.llvm.org/download.html#10.0.1) ## ask isn't it included with the repo
This is not a requirement.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +    The path for this will be used in this [section](#exporting-onnx-path-variables)
Recheck path.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +>TODO: mlbridge.yml should be replaced with a unanimous env
What is this?

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +* Other python requirements are available in [mlbridge.yml]
Broken path.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +conda env create -f ./mlgo-new.yml
Can we rename the file and related things to `mlopt`?

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +cmake -G "Unix Makefiles" -S ../llvm -B . \
This need not have INLINER_MODEL and RAEVICT_MODEL related paths. Please remove and test. Then make changes.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +cmake -G "Unix Makefiles" -S ../llvm -B . \
This need not be Makefile. It could be any generator that LLVM supports.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +make clang opt -j50
Make it generic please. make, j50 could be written better.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +> Do not make all, your build will break. Only make clang and opt
You can say make all is broken now and we will be fixing it.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +to learn more head to the Pass specific readme [here].
broken link

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +```
Please add path to the pass.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +POSET-RL uses a reinforcement learning approach as the search space of optimization sequences is too big to enumerate. For a compiler with m optimization passes, if the sequence length is fixed as n,
Not much details are required. Please reduce.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +POSET-RL uses a reinforcement learning approach as the search space of optimization sequences is too big to enumerate. For a compiler with m optimization passes, if the sequence length is fixed as n,
Add links to the paper, webpage, etc.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +POSET-RL uses a reinforcement learning approach as the search space of optimization sequences is too big to enumerate. For a compiler with m optimization passes, if the sequence length is fixed as n,
Also point to the pass.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +> POSET-RL: Phase ordering for Optimizing Size and Execution Time using Reinforcement Learning: Shalini Jain, Yashas Andaluri, S. VenkataKeerthy and Ramakrishna Upadrasta
Please add conference name and year. It should be ISPASS 2022.

2024-02-28 11:07 UTC, svkeerthy commented on README.md
Please add reference to the paper like what you have in distribution and poset-rl

2024-02-28 11:07 UTC, svkeerthy commented on README.md
> +> Reinforcement Learning assisted Loop Distribution for Locality and Vectorization, Shalini Jain, S. VenkataKeerthy, Rohit Aggarwal, Tharun Kumar Dangeti, Dibyendu Das, Ramakrishna Upadrasta
Add conference venue and year. It should be LLVM-HPC, 2022.

2024-02-28 13:01 UTC, mvvsmk commented on README.md
> +    The path for this will be used in this [section](#exporting-onnx-path-variables)
need clarification

2024-02-28 13:33 UTC, mvvsmk commented on README.md
> +>TODO: mlbridge.yml should be replaced with a unanimous env
@svkeerthy This was supposed to be one mlbrigde.yml a common virtual env for all envs.

2024-03-01 12:45 UTC, svkeerthy requested changes

2024-03-01 12:45 UTC, svkeerthy commented on README.md
> +#### A small hack to prevent the conda environtments from clashing (To Be removed)
Please recheck if this is needed anymore.

2024-03-01 12:45 UTC, svkeerthy commented on README.md
> +Please see [here](https://compilers.cse.iith.ac.in/publications/rl_loop_distribution/) for more details. [Website link](https://compilers.cse.iith.ac.in/publications/rl_loop_distribution/)
Both are same links?

2024-03-01 12:45 UTC, svkeerthy commented on README.md
> +Please see [here](https://compilers.cse.iith.ac.in/publications/rl4real/) for more details. [Website link](https://compilers.cse.iith.ac.in/publications/rl4real/)
Please recheck

2024-03-01 12:45 UTC, svkeerthy commented on README.md
> +>RL4ReAl: Reinforcement Learning for Register Allocation : S. VenkataKeerthy, Siddharth Jain, Anilava Kundu, Rohit Aggarwal, Albert Cohen, Ramakrishna Upadrasta CC 2023
Please add ','

2024-03-01 13:31 UTC, svkeerthy approved these changes

2024-03-01 13:32 UTC, merged